stages:
  - build

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context ${CI_PROJECT_DIR}/lmod --cache=true --cache-copy-layers=true --destination ${CI_REGISTRY_IMAGE}-lmod:${CI_COMMIT_TAG} --destination ${CI_REGISTRY_IMAGE}-lmod:latest
    - /kaniko/executor --context ${CI_PROJECT_DIR}/venv --cache=true --cache-copy-layers=true --destination ${CI_REGISTRY_IMAGE}-venv:${CI_COMMIT_TAG} --destination ${CI_REGISTRY_IMAGE}-venv:latest
  rules:
    - if: $CI_COMMIT_TAG
