stages:
  - build

build-docker:
  stage: build
  image: moby/buildkit:latest
  script:
    - mkdir -p ~/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY_DOCKERHUB\":{\"username\":\"$CI_REGISTRY_DOCKERHUB_USER\",\"password\":\"$CI_REGISTRY_DOCKERHUB_PASSWORD\"}}}" > ~/.docker/config.json
    - buildkitd &
    - sleep 5
    - buildctl build --frontend dockerfile.v0 --local context=${CI_PROJECT_DIR} --output type=image,name=${CI_REGISTRY_DOCKERHUB_BASEIMAGE}/notebook:${CI_COMMIT_TAG},push=true --output type=image,name=${CI_REGISTRY_DOCKERHUB_BASEIMAGE}/notebook:latest,push=true
  rules:
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/'

build-gitlab:
  stage: build
  image: moby/buildkit:latest
  script:
    - mkdir -p ~/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > ~/.docker/config.json
    - buildkitd &
    - sleep 5
    - buildctl build --frontend dockerfile.v0 --local context=${CI_PROJECT_DIR} --output type=image,name=${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG},push=true
  rules:
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+(-.+)$/'

build-commit:
  stage: build
  image: moby/buildkit:latest
  script:
    - mkdir -p ~/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > ~/.docker/config.json
    - buildkitd &
    - sleep 5
    - buildctl build --frontend dockerfile.v0 --local context=${CI_PROJECT_DIR} --output type=image,name=${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA},push=true
  when: manual
